sudo: true
language: node_js
node_js:
  - "4"
  - "6"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq firebird2.5-super firebird2.5-dev
  - sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i /etc/default/firebird2.5
  - sudo service firebird2.5-super start
  - echo 'CREATE DATABASE "LOCALHOST:/tmp/hapi_node_firebird.fdb" PAGE_SIZE = 16384;' > /tmp/create_hapi_node_firebird_test.sql
  - isql-fb -u SYSDBA -p masterkey -i /tmp/create_hapi_node_firebird_test.sql -q
env:
  - CC=clang CXX=clang++ npm_config_clang=1